### ISSUE TITLE
Issue on converting project with rotated object (related to issue #19)

### ISSUE THREAD

**Issue by DingoTom** [dlintott/gns3-converter#23]
Hi, Tried importing with latest version on my GNS3. First time I got the two un-rotated coloured circles come across and no rotated circle with the error below. Shut down and tried again and this time no circles came across but same error.

thanks

GNS3 management console. Running GNS3 version 1.2.3 on Linux (64-bit).
Copyright (c) 2006-2014 GNS3 Technologies.

=> ****** Exception detected, traceback information saved in /root/.config/GNS3/exception.log ******

PLEASE REPORT ON https://community.gns3.com/community/support/bug

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.2.3-py3.4.egg/gns3/dialogs/new_project_dialog.py", line 99, in _openProjectActionSlot
    self._main_window.openProjectActionSlot()
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.2.3-py3.4.egg/gns3/main_window.py", line 452, in openProjectActionSlot
    if self.loadProject(path):
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.2.3-py3.4.egg/gns3/main_window.py", line 1375, in loadProject
    self._convertOldProject(path)
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.2.3-py3.4.egg/gns3/main_window.py", line 1360, in _convertOldProject
    self.loadProject(project_path)
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.2.3-py3.4.egg/gns3/main_window.py", line 1406, in loadProject
    topology.load(json_topology)
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.2.3-py3.4.egg/gns3/topology.py", line 644, in load
    ellipse_item.load(topology_ellipse)
  File "/usr/lib/python3.4/site-packages/gns3_gui-1.2.3-py3.4.egg/gns3/items/shape_item.py", line 302, in load
    self.setRotation(rotation)
TypeError: QGraphicsItem.setRotation(float): argument 1 has unexpected type 'str'

**Comment by dlintott** [comment]
Okay, I think I know what the issue is here (mistmatch of data types). 

I shall have a look when I'm back home
